- name: backup mysql db server
  shell: >
    mysqldump \
      -u {{ db_pull_remote_database_user }} \
      --password={{ db_pull_remote_database_password }} \
      -h {{ db_pull_remote_database_host }} \
      {{ db_pull_remote_database_name }} \
      > {{ db_pull_remote_backup_path }}/{{ db_pull_remote_database_name }}-{{ ansible_date_time.iso8601 }}.dump
